version: "3.9"

services:
  app:
    container_name: sql-translation-api
    image: sql-translation-api:prod
    ports:
      - "3100:3100"
    command: gunicorn --bind 0.0.0.0:3100 app:app

networks:
  proxynet:
    name: custom_network
